### ISSUE TITLE
SuperPoint-Loss import issue

### ISSUE THREAD

**Issue by Omni-HuB** [WildlifeDatasets/wildlife-tools#13]
unlike Triplet-Loss and Arcface-Loss, cannot import SuperPoint-Loss from the wildlife-tools package 
"Shows error; no such module was found."

![image](https://github.com/user-attachments/assets/6e356b9b-2a57-414f-9548-82118191666d)

<be>

![image](https://github.com/user-attachments/assets/a10bde19-519d-4ac6-bf47-28849afafbd5)

**Comment by picekl** [comment]
Hi @Omni-HuB,

Thank you for you report.

What do you mean by SuperPoint-Loss? There is nothing like SupperPoint-Loss.
If you mean the SuperPoint "feature extractor," we are currently working on a new version that uses a different library on the backend and should work. We expect its release at the end of the week. I will keep you updated.

Best,
Lukas

**Comment by AndrasZabo** [comment]
Hi @VojtechCermak,

Thanks for your reply! I've read the WildFusion paper, great work, congrats!
I see that you have also implemented DISK and ALIKED, exciting, I'll try them out!

Best,
Andras
