### ISSUE TITLE
Unable to find the definition for "SplitMetadata"

### ISSUE THREAD

**Issue by skyprince999** [WildlifeDatasets/wildlife-tools#17]
The definition for `SplitMetadata` seems to be missing. I couldnt find it in the library/github repo 

`from wildlife_tools.data import WildlifeDataset, SplitMetadata`

Error: 
'cannot import name 'SplitMetadata' from 'wildlife_tools.data''

**Comment by VojtechCermak** [comment]
Hi,
Thank you for noticing.  If you encounter it in the baseline notebooks, it is caused by them not being updated to the latest version. I have updated the notebooks now.

But you can always delete the import and use this instead:
`metadata.query('split == "train"')`
