### ISSUE TITLE
ModuleNotFoundError: No module named 'kornia'

### ISSUE THREAD

**Issue by crkarthik11** [WildlifeDatasets/wildlife-tools#5]
Hi, 

When I tried to set the project with a working example I encountered the following error,

```

[/usr/local/lib/python3.10/dist-packages/wildlife_tools/similarity/loftr.py](https://localhost:8080/#) in <module>
      3 import pandas as pd
      4 from tqdm import tqdm
----> 5 import kornia.feature as KF
      6 import itertools
      7 from wildlife_tools.similarity.base import Similarity

ModuleNotFoundError: No module named 'kornia'
```
### Fix

`pip install kornia
`

It would be nice if it is either documented or added to the project dependency

**Comment by VojtechCermak** [comment]
Hi, 
thank you for raising the issue. 
Now kornia is correctly added as dependency in pyproject.
